"use client";
import React from "react";
import { Typography } from "@/components/uikit/Typography/Typography";
import { Divider } from "@/components/uikit/Divider/Divider";
import {
  PageWrapper,
  HeaderSection,
  ContentWrapper,
  TermSection,
  FooterSection,
} from "./page.styles";

const Page = () => {
  return (
    <PageWrapper>
      <HeaderSection>
        <Typography variant="h3" text="Terms of Service" align="center" />
        <Typography
          variant="subtitle1"
          text="Effective Date: April 13, 2026"
          align="center"
          color="textSecondary"
        />
      </HeaderSection>

      <Divider />

      <ContentWrapper>
        <TermSection>
          <Typography variant="h5" text="1. Acceptance of Terms" />
          <Typography
            variant="body1"
            text="By accessing or using Fiddle (the 'Platform'), you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use the Platform. Fiddle provides a specialized marketplace for one-time IT projects and freelance engagements."
          />
        </TermSection>

        <TermSection>
          <Typography variant="h5" text="2. User Eligibility" />
          <Typography
            variant="body1"
            text="The Platform is intended for use by IT professionals and businesses. You must be at least 18 years of age and capable of entering into legally binding contracts to create an account. You are responsible for all activity that occurs under your account."
          />
        </TermSection>

        <TermSection>
          <Typography variant="h5" text="3. Project Engagements" />
          <Typography
            variant="body1"
            text="Fiddle facilitates the matching of Freelancers and Clients for specific, one-time IT deliverables. Each project is a separate agreement between the parties. Fiddle is not a party to these agreements but provides the infrastructure for search, communication, and fulfillment tracking."
          />
        </TermSection>

        <TermSection>
          <Typography variant="h5" text="4. Work Search and Visibility" />
          <Typography
            variant="body1"
            text="Our advanced search algorithms specialized for the IT field help users find relevant opportunities and talent. By listing your skills or projects, you grant Fiddle the right to display this information to other registered users of the Platform."
          />
        </TermSection>

        <TermSection>
          <Typography variant="h5" text="5. Intellectual Property" />
          <Typography
            variant="body1"
            text="All work products produced through the Platform are subject to the specific IP agreements reached between the Freelancer and the Client. Fiddle claims no ownership over the data or code generated by its users during project execution."
          />
        </TermSection>

        <TermSection>
          <Typography variant="h5" text="6. Payments and Fees" />
          <Typography
            variant="body1"
            text="Platform usage may involve service fees as detailed in our pricing schedule. Payments for projects must be processed through our authorized payment gateways to ensure transparency and security for all parties involved."
          />
        </TermSection>

        <TermSection>
          <Typography variant="h5" text="7. Termination" />
          <Typography
            variant="body1"
            text="We reserve the right to suspend or terminate access to the Platform at our discretion, without notice, for behavior that violates these Terms or harms the integrity of the professional IT community we support."
          />
        </TermSection>
      </ContentWrapper>

      <Divider />

      <FooterSection>
        <Typography
          variant="body2"
          text="These terms are subject to change. Continued use of Fiddle constitutes acceptance of any modifications."
        />
      </FooterSection>
    </PageWrapper>
  );
};


export default Page;
