services:
  app:
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run build &&
             npm run start"
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
