import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto } from "next/font/google";
import theme from "@/theme";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { GlobalStyles } from "@/components/uikit/GlobalStyles/GlobalStyles";
import { ModalProvider } from "@/components/ModalProvider/ModalProvider";
import { QueryProvider } from "@/components/QueryProvider/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <QueryProvider>
              <ModalProvider>
                <CssBaseline />
                <GlobalStyles />
                {children}
              </ModalProvider>
            </QueryProvider>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
